# Generated by Django 5.1.5 on 2025-01-29 10:14

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(default=shortener.models.generate_short_code, max_length=10, unique=True),
        ),
    ]
