# Generated by Django 5.1.5 on 2025-01-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_created_by_shortenedurl_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
